name: Tests

on:
  push

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [16.x]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Cache NPM cache
              uses: actions/cache@v2
              id: npm
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-npm-v2-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-npm-v2-
            - name: Install Dependencies
              run: npm ci
            - name: Backend Tests
              run: npm run test:backend -- --coverage
            - name: Coveralls Backend
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                flag-name: backend
            - name: Frontend Tests
              run: npm run test:frontend -- --coverage
            - name: Coveralls Frontend
              uses: coverallsapp/github-action@master
              with:
                github-token: ${{ secrets.GITHUB_TOKEN }}
                flag-name: frontend
